snowflake_project:
  outputs:
    dev:
      account: #
      password: #
      database: DBT_DEV
      role: ACCOUNTADMIN
      schema: STAGING
      threads: 1
      type: snowflake
      user: #
      warehouse: COMPUTE_WH
  target: dev
